-- =============================================================================
-- Blur previews for locked teaser tiles
--
-- Extends the tiles from 0008 so the blur is the ACTUAL piece rather than
-- decorative artwork: a ~20x25 pixel version of its first photograph, stored
-- inline and upscaled behind the blur in the browser.
--
-- ── Why this is not "the photograph, blurred" ────────────────────────────────
-- The real file is never sent. `product-images` stays private, and the storage
-- policy in 0003 is untouched — a guest still cannot fetch a photograph of a
-- piece they may not see. What they get is a separate, deliberately tiny
-- derivative of about 500 pixels total.
--
-- That size is the whole security argument, and it is a different argument from
-- a CSS blur. A CSS blur hides detail that is still present in the file, and
-- comes off with one devtools click. Here the detail was destroyed when the
-- derivative was made: there is no filter to remove and nothing to recover,
-- because 500 pixels cannot be upscaled back into a photograph. What survives
-- is silhouette and colour — enough to see that a piece is a gold necklace
-- rather than a ring, which is the point of the tile.
--
-- Generated by tools/generate-blur-previews.mjs for existing rows, and by the
-- admin panel on upload for new ones. Null is expected and handled: the tile
-- falls back to the decorative artwork it used before.
-- =============================================================================

alter table public.products
  add column if not exists blur_preview text;

comment on column public.products.blur_preview is
  'Base64 data URI, ~20x25px, of the first gallery image. Shown blurred to '
  'viewers who may not open the piece. Never the full photograph — see '
  'migration 0009. Generated by tools/generate-blur-previews.mjs.';

-- A stray full-size image pasted in here would hand over the photograph this
-- whole design avoids sending, and it would do it silently. ~500 pixels of
-- JPEG is under 1 KB; 4 KB leaves generous headroom without leaving room for
-- a real photograph.
alter table public.products
  drop constraint if exists products_blur_preview_is_tiny;

alter table public.products
  add constraint products_blur_preview_is_tiny check (
    blur_preview is null
    or (blur_preview like 'data:image/jpeg;base64,%' and length(blur_preview) <= 4096)
  );


-- -----------------------------------------------------------------------------
-- locked_teasers(), extended
-- -----------------------------------------------------------------------------

-- The return type gains a column, which `create or replace` cannot do.
drop function if exists public.locked_teasers(text);

create or replace function public.locked_teasers(p_category_slug text default null)
returns table (
  visibility    public.visibility,
  category_id   uuid,
  category_name text,
  category_slug text,
  blur_preview  text
)
language sql
stable
security definer
set search_path = public
as $$
  select p.visibility, c.id, c.name, c.slug, p.blur_preview
  from public.products p
  left join public.categories c on c.id = p.category_id
  where p.is_active
    -- The complement of the products policy, derived from the same function,
    -- so the two cannot drift: a piece is either shown or blurred, never both
    -- and never neither.
    and not (p.visibility = any (public.visible_levels()))
    and (
      p_category_slug is null
      -- A top-level slug takes its sub-categories with it, matching how
      -- listProducts scopes a category. A sub-category slug matches itself.
      or c.slug = p_category_slug
      or c.parent_id = (
        select id from public.categories where slug = p_category_slug and is_active
      )
    )
    -- A category hidden by the admin should not be advertised by its teasers.
    and (c.id is null or c.is_active)
  order by p.sort_order;
$$;

-- Still no id, no name, no slug, no storage_path. The select list above remains
-- the security argument for this function; adding a column to it changes what
-- the platform leaks.
revoke all on function public.locked_teasers(text) from public;
grant execute on function public.locked_teasers(text) to anon, authenticated;
